### ISSUE TITLE
[develop/pwa2] 반응형 UI 구현

### ISSUE THREAD

**Issue by kangsinbeom** [Goorm-Lucky7/Dart_FE#105]
### 🎯 Tasks

- [ ] 알림창 반응형 구현
- [ ] 회원가입 로그인 페이지 반응형 구현
- [ ] 회원가입 시 생년월일 필수로 받기
- [x] 후기 작성 반응형 구현

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
