### ISSUE TITLE
[develop/pwa-02] 반응형 UI 구현 및 마무리

### ISSUE THREAD

**Issue by gamjatan9** [Goorm-Lucky7/Dart_FE#110]
### 🎯 Tasks

- [x] 마이페이지 반응형 구현
- [x] 결제 페이지 반응형 구현
- [x] 코드 개선 및 리팩토링

### 🎯 Images

<details>
<summary>작업 이미지</summary>
<img width="686" alt="image" src="https://github.com/Goorm-Lucky7/Dart_FE/assets/122338050/a394f2df-ac35-4eb9-8ddf-4722007feefa">

</details>
