### ISSUE TITLE
[develop/upgrade] 무손실 압축, 화면캡처 방지 / 마무리

### ISSUE THREAD

**Issue by j2an777** [Goorm-Lucky7/Dart_FE#113]
### 🎯 Tasks

- [ ] 무손실 압축 구현
- [ ] 화면캡처 방지 알아보기
- [ ] 템플릿 추가 고려
- [ ] 코드 리팩토링
- [ ] 컨테이너 쿼리 학습

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
