### ISSUE TITLE
[develop/testcode] 자동화 테스트 환경 설정 및 테스트 코드 작성

### ISSUE THREAD

**Issue by kangsinbeom** [Goorm-Lucky7/Dart_FE#157]
### 🎯 Tasks

- [ ] 자동화 테스트 환경 구축 (Jest)
- [ ] 유닛 테스트 코드 작성
- [ ] 통합 테스트 코드 작성
- [ ] 테스트 코드 작성 후 블로그 작성

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
