### ISSUE TITLE
[develop/portal] createPortal 개선

### ISSUE THREAD

**Issue by kangsinbeom** [Goorm-Lucky7/Dart_FE#158]
### 🎯 Tasks

- [ ] 컨텐츠에 대한 포탈을 모듈화시키기
- [ ] zustand를 이용한 상태를 확장가능한 base 만들기 
- [ ] 포탈 테스트 후 완료되면 배포

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
