### ISSUE TITLE
[develop/authApis] 로그인 회원가입 api적용 및 유저 데이터 관리

### ISSUE THREAD

**Issue by kangsinbeom** [Goorm-Lucky7/Dart_FE#16]
### 🎯 Tasks

- [x] 로그인 api 적용
- [x] 회원가입 api 적용
- [ ] 회원가입 중복 아이디 검증창 띄우기
- [ ] 회원가입 이메일 검증창 띄우기
- [ ] navbar 반응형 ui 수정
- [x] jwt 디코딩해서 데이터 받기 및 체계 구현
- [x] 정보수정 시 jwt 받기 얘기 전달하기

### 🎯 Images

<details>
<summary>작업 이미지</summary>

UI 작업이 없습니다.

</details>
