### ISSUE TITLE
[develop/api] 각 페이지 api 구현 및 리디자인

### ISSUE THREAD

**Issue by j2an777** [Goorm-Lucky7/Dart_FE#22]
### 🎯 Tasks

- [ ] react hook form 공부하기
- [x] 전시관 mock data 생성
- [x] msw 테스트
- [ ] 작품 설명 모달 리디자인

### 🎯 Images

<details>
<summary>작업 이미지</summary>

UI 작업이 없습니다.

</details>
