### ISSUE TITLE
[develop/mypage] 마이페이지 UI 구현

### ISSUE THREAD

**Issue by gamjatan9** [Goorm-Lucky7/Dart_FE#26]
### 🎯 Tasks

- [x] 마이페이지 UI 구현
- [x] 사용자 정보(닉네임, 아이디, 소개글)
- [x] 구매/전시 탭 메뉴 구분
- [x] 티켓 컴포넌트

### 🎯 Images

<details>
<summary>작업 이미지</summary>

<img width="1032" alt="image" src="https://github.com/Goorm-Lucky7/Dart_FE/assets/122338050/6c8eee8e-a206-4aeb-83f1-1bd5b83060e7">

</details>
