### ISSUE TITLE
[develop/editapi] 회원정보수정, 전시설명 모달 api 구현

### ISSUE THREAD

**Issue by j2an777** [Goorm-Lucky7/Dart_FE#27]
### 🎯 Tasks

- [ ] 회원정보수정 msw 마무리
- [ ] 전시 설명 모달 msw 테스트
- [ ] 전시 페이지 carousel 라이브러리 구현
- [ ] 작품 설명 모달 리디자인

<details>
<summary>작업 이미지</summary>

</details>
