### ISSUE TITLE
[develop/apiintro] api 마무리 및 애니메이션 구현

### ISSUE THREAD

**Issue by j2an777** [Goorm-Lucky7/Dart_FE#34]
### 🎯 Tasks

- [ ] 회원정보 수정 api 마무리
- [ ] 전시 설명 api 마무리
- [ ] framer motion 학습
- [ ] 스크롤 애니메이션 구현

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
