### ISSUE TITLE
[develop/improveUI] UI 개선 및 수정

### ISSUE THREAD

**Issue by gamjatan9** [Goorm-Lucky7/Dart_FE#38]
### 🎯 Tasks

- [x] 마이페이지 페이지네이션
- [x] 전시 생성 UI 개선
  - [x] input form state 유지
  - [x] 스크롤 유지
  - [x] 이미지 dropzone 수정

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
