### ISSUE TITLE
[develop/plusapi] 회원정보수정 api, 전시 페이지 마무리

### ISSUE THREAD

**Issue by j2an777** [Goorm-Lucky7/Dart_FE#45]
### 🎯 Tasks

- [x] 회원정보 수정 api 마무리
- [x] 닉네임 중복 체크 api 마무리
- [x] 전시 페이지 20개 데이터 UI 구현
- [x] 애니메이션 추가 학습

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
