### ISSUE TITLE
[develop/gallery] 전시 페이지 업그레이드

### ISSUE THREAD

**Issue by j2an777** [Goorm-Lucky7/Dart_FE#51]
### 🎯 Tasks

- [ ] 전시 페이지 코드 리팩토링
- [ ] 캡처방지, 워터마크 자동생성 알아보기
- [ ] 템플릿 추가 기획
- [ ] 페이지 전환 애니메이션 추가
- [ ] 

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
