### ISSUE TITLE
[develop/uiresult] UI TEST 결과 개선 및 공통 컴포넌트 생성

### ISSUE THREAD

**Issue by kangsinbeom** [Goorm-Lucky7/Dart_FE#58]
### 🎯 Tasks

- [ ] 에러 바운더리 생성 및 적용
- [x] ui test 결과 개선
- [ ] 검색 기능 완성

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
