### ISSUE TITLE
[develop/galleryplus] 전시 페이지 템플릿 추가, 회원정보 수정, 전시 페이지 api 마무리

### ISSUE THREAD

**Issue by j2an777** [Goorm-Lucky7/Dart_FE#63]
### 🎯 Tasks

- [ ] 전시 템플릿 추가(4 ~ 6개)
- [ ] 회원정보 수정 api 테스트
- [ ] 전시 페이지 api 마무리
- [ ] 워터마크 자동생성 공부

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
