### ISSUE TITLE
[develop/eventui] 이벤트 페이지 ui 및 미완료 과제

### ISSUE THREAD

**Issue by kangsinbeom** [Goorm-Lucky7/Dart_FE#66]
### 🎯 Tasks

- [x] 이벤트 페이지 UI
- [ ] onError 모듈화
- [ ] scroll처리 (검색창, 알림, 댓글리스트)
- [x] 에러바운더리 적용 및 대체 ui 생성
- [x] 회원가입 refresh 처리

### 🎯 Images

<details>
<summary>작업 이미지</summary>

![주문 결제 페이지](https://github.com/Goorm-Lucky7/Dart_FE/assets/83047601/ab39a1f5-7da5-40ce-8ceb-1f8798a7afb9)
![쿠폰 조회 페이지](https://github.com/Goorm-Lucky7/Dart_FE/assets/83047601/431db9b7-6812-48d3-830f-6b91a9aa67ca)
![쿠폰 조회 페이지111](https://github.com/Goorm-Lucky7/Dart_FE/assets/83047601/33940afe-1c74-4572-bc2b-dd8279b93f5d)

</details>
