### ISSUE TITLE
[develop/improvemvp] 채팅, 결제, 전시 생성 개선

### ISSUE THREAD

**Issue by gamjatan9** [Goorm-Lucky7/Dart_FE#69]
### 🎯 Tasks

- [x] 웹소켓 연결 오류 해결
- [x] 실시간 채팅 구현
- [x] 실시간 접속자 구현
- [x] 결제 페이지 기능 구현
- [ ] 전시 생성 제한 사항 에러 메세지 띄우기
- [x] 결제 승인 페이지 다른 유저 못 들어가게 막기

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
