### ISSUE TITLE
[develop/galleryplus2]

### ISSUE THREAD

**Issue by j2an777** [Goorm-Lucky7/Dart_FE#70]
### 🎯 Tasks

- [ ] 전시 페이지 템플릿 추가 마무리
- [ ] 회원정보 수정 api 마무리
- [ ] 워터마크 자동생성 알아보기

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
