### ISSUE TITLE
[develop/share] 공유하기 구현, 워터마크 서치

### ISSUE THREAD

**Issue by j2an777** [Goorm-Lucky7/Dart_FE#74]
### 🎯 Tasks

- [ ] 공유하기 기능 알아보기
- [ ] 워터마크 자동생성 알아보기
- [ ] (후 순위) 알림 기능 관련으로 서치

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
