### ISSUE TITLE
[develop/shared] 공통 컴포넌트 마무리 및 이벤트 페이지 기능 구현

### ISSUE THREAD

**Issue by kangsinbeom** [Goorm-Lucky7/Dart_FE#78]
### 🎯 Tasks

- [x] 에러 처리 마무리
- [ ] 스크롤 기능 구현
- [x] 이벤트 페이지 마무리
- [x] 기능 점검 및 필요사항 구현

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
