### ISSUE TITLE
[develop/improvements] 실시간 기능 및 기타 오류 개선

### ISSUE THREAD

**Issue by gamjatan9** [Goorm-Lucky7/Dart_FE#80]
### 🎯 Tasks

- [ ] 채팅 오류 해결
- [x] 접속자 오류 해결
- [x] 전시생성 에러 처리
- [x] 결제 수정

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
