### ISSUE TITLE
[develop/impress] 이미지 압축 학습, UI 테스트 반영

### ISSUE THREAD

**Issue by j2an777** [Goorm-Lucky7/Dart_FE#88]
### 🎯 Tasks

- [ ] 이미지 압축 학습
- [ ] 이용 약관 양식 스타일 수정
- [ ] UI 테스트 반영

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
