### ISSUE TITLE
[develop/detailui] 에러, 작품설명 모달, 전시설명 모달 UI 구현

### ISSUE THREAD

**Issue by j2an777** [Goorm-Lucky7/Dart_FE#9]
### 🎯 Tasks

- [] 에러페이지 UI 구현
- [] 작품설명 모달창 UI 리디자인
- [] 전시설명 모달창 UI 구현
- [x] 채팅창 클릭 리스너 함수 호출 구문 마련
- [ ] msw 테스트

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
