### ISSUE TITLE
[develop/issues] 실시간 기능 및 기타 오류 해결

### ISSUE THREAD

**Issue by gamjatan9** [Goorm-Lucky7/Dart_FE#94]
### 🎯 Tasks

- [x] 채팅 연결 오류 해결
- [x] 접속자 기능 수정
- [x] 기타 오류 해결

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
