### ISSUE TITLE
[develop/reactui] 반응형 UI 및 마무리

### ISSUE THREAD

**Issue by j2an777** [Goorm-Lucky7/Dart_FE#97]
### 🎯 Tasks

- [ ] 반응형 UI
- [ ] 공유하기 url 변경
- [ ] 회원정보 수정 완료 처리
- [ ] 무손실 압축 구현

### 🎯 Images

<details>
<summary>작업 이미지</summary>

</details>
