### ISSUE TITLE
[develop/pwa-01] 반응형UI 구현

### ISSUE THREAD

**Issue by gamjatan9** [Goorm-Lucky7/Dart_FE#98]
### 🎯 Tasks

  - [ ] 전시 생성 페이지 반응형 UI
  - [ ] 결제페이지 반응형 UI
  - [ ] 마이페이지 반응형 UI

### 🎯 Images

<details>
<summary>작업 이미지</summary>
<img width="1149" alt="image" src="https://github.com/Goorm-Lucky7/Dart_FE/assets/122338050/bd43d39d-e238-4cca-a98e-67a254fac148">

</details>
